blank_issues_enabled: true
contact_links:
  - name: Questions or Discussion
    url: https://github.com/cj-taylor/codeyou-cohort-tracker/discussions
    about: Have a question or want to chat about the project? Start a discussion.
